# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseNode@1
  inputs:
    version: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install --global yarn
    yarn
    yarn build
    pwd
    ls
  displayName: 'npm install and build'
  
- script: |
    pwd
    ls
    mkdir -p .ssh
    touch .ssh/priv_key
    echo $(AWS_SSH_PRIVATE_KEY_TEST) >> .ssh/priv_key
    cat .ssh/priv_key
    scp -r -i .ssh/priv_key build/* bitnami@18.142.150.173:/opt/bitnami/nginx/html
  displayName: 'Copy the build folder to AWS LightSail'