# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: InstallSSHKey@0
  displayName: 'Install an SSH key'
  inputs:
    knownHostsEntry: 18.142.150.173
    sshKeySecureFile: 'LightsailDefaultKey-ap-southeast-1.pem'

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'LightsailDefaultKey-ap-southeast-1.pem' # Replace with the file alias of your private key file

- task: UseNode@1
  inputs:
    version: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install --global yarn
    yarn
    yarn build
    pwd
    ls
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'build'
    TargetFolder: 'bitnami@18.142.150.173:/opt/bitnami/nginx/html'
    OverWrite: true
    Advanced: |
      -i $(Agent.TempDirectory)/LightsailDefaultKey-ap-southeast-1.pem 

- script: |
    ls
    scp -r build/* bitnami@18.142.150.173:/opt/bitnami/nginx/html
  displayName: 'Copy the build folder to AWS LightSail'