# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseNode@1
  inputs:
    version: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install --global yarn
    yarn
    yarn build
    pwd
    ls
  displayName: 'npm install and build'
  
- script: |
    pwd
    ls
    az login --service-principal -u $(servicePrincipalId) -p $(servicePrincipalKey) --tenant $(tenantId)
    aws configure set aws_access_key_id $(awsAccessKey)
    aws configure set aws_secret_access_key $(awsSecretKey)
    aws configure set default.region $(awsRegion)
  displayName: 'Configure Azure and AWS CLI tools'